# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: publish release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js Active LTS version
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Build
      run: |
        npm ci
        npm run build --if-present

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: dist/sakura-calculator.min.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
